from crewai import Task
from loguru import logger


def create_tasks(eligibility_analyst, trial_matcher, report_writer, patient_profile: dict) -> list[Task]:
    """
    3 tasks in sequential order.
    In CrewAI sequential process: Task N's output is injected into Task N+1's context automatically.
    """

    patient_summary = f"""
Patient Profile:
- Name: {patient_profile.get('name')}
- Age: {patient_profile.get('age')}
- Diagnosis: {patient_profile.get('diagnosis')}
- Comorbidities: {', '.join(patient_profile.get('comorbidities', []))}
- Current Medications: {', '.join(patient_profile.get('current_medications', []))}
- Prior Treatments: {', '.join(patient_profile.get('prior_treatments', []))}
- Lab Values: {patient_profile.get('lab_values', {})}
- Trial Phase Preference: {patient_profile.get('trial_phase_preference', 'any')}
"""

    task_1 = Task(
        description=f"""
You are reviewing a patient for clinical trial eligibility.

{patient_summary}

Steps:
1. Use the clinical_trial_retriever tool to search for relevant trials using the patient's diagnosis and key lab values.
2. For each retrieved trial, go through EVERY inclusion and exclusion criterion one by one.
3. For each criterion, state: MET / NOT MET / UNKNOWN (if patient data is missing).
4. List the supporting evidence from the patient profile for each decision.

Output format (for each trial):
TRIAL: [trial_id]
- Criterion: [criterion text] → STATUS: MET/NOT MET/UNKNOWN | Evidence: [patient data]
""",
        expected_output=(
            "A detailed per-criterion eligibility breakdown for each retrieved trial. "
            "Every criterion must have a MET/NOT MET/UNKNOWN verdict with evidence."
        ),
        agent=eligibility_analyst,
    )

    task_2 = Task(
        description=f"""
Using the eligibility analysis from the previous task, rank the top 3 most suitable trials for this patient.

{patient_summary}

Scoring rules:
- Start at 100, deduct points for each NOT MET criterion (hard exclusion = -50, soft = -20)
- Deduct 5 points for each UNKNOWN criterion
- If ANY hard exclusion criterion is NOT MET → trial score = 0, mark INELIGIBLE

For each top 3 trial, provide:
- trial_id
- title
- condition
- phase
- match_score (0–100)
- eligibility_status: ELIGIBLE (score ≥ 70) | POTENTIALLY_ELIGIBLE (40–69) | INELIGIBLE (< 40)
- met_criteria: list of MET criterion summaries
- unmet_criteria: list of NOT MET criterion summaries
- reasoning: 2–3 sentence explanation of the score
""",
        expected_output=(
            "A ranked list of the top 3 matching trials with match_score, "
            "eligibility_status, met_criteria, unmet_criteria, and reasoning for each."
        ),
        agent=trial_matcher,
        context=[task_1],
    )

    task_3 = Task(
        description=f"""
Using the ranked trial matches from the previous task, generate a structured physician report.

{patient_summary}

Output ONLY valid JSON in this exact structure:
{{
    "top_trials": [
        {{
            "trial_id": "string",
            "title": "string",
            "condition": "string",
            "phase": "string",
            "match_score": 0.0,
            "eligibility_status": "ELIGIBLE | POTENTIALLY_ELIGIBLE | INELIGIBLE",
            "met_criteria": ["string"],
            "unmet_criteria": ["string"],
            "reasoning": "string"
        }}
    ],
    "report": {{
        "summary": "2-3 sentence summary of best match and overall eligibility landscape",
        "recommendation": "Which trial to pursue first and why",
        "disclaimer": "This report is generated by an AI system for physician review only. Final eligibility must be confirmed by a qualified clinical research coordinator. This does not constitute medical advice."
    }}
}}

Output ONLY the JSON object. No preamble, no explanation, no markdown fences.
""",
        expected_output=(
            "Valid JSON object matching the exact schema above. "
            "Must include disclaimer. No markdown, no extra text."
        ),
        agent=report_writer,
        context=[task_2],
    )

    logger.info("All 3 CrewAI tasks created")
    return [task_1, task_2, task_3]